### ISSUE TITLE
Error: Bucket names cannot contain forward slashes

### ISSUE THREAD

**Issue by GeorgiMateev** [awslabs/aws-ai-tracking-bot#1]
Hello,
I got the following error in CodeBuild when launched the stack. The stack is created successfully but the Lex bot is missing.

stdout

19:22:13
<info> timestamp is: 1497554533

19:22:13
<error> Could not add zip to s3 bucket. Pipeline stopped: InvalidBucket: Bucket names cannot contain forward slashes. Bucket: trackingbot-artifactstore-14bqw9w9xtexq/artifacts

19:22:13
<error> Could not build function zip in s3InvalidBucket: Bucket names cannot contain forward slashes. Bucket: trackingbot-artifactstore-14bqw9w9xtexq/artifacts

19:22:13

19:22:13
stderr

19:22:13

19:22:13
failed to create lex app and bot: undefined

19:22:13

19:22:13
[Container] 2017/06/15 19:22:13 Command did not exit successfully node masterBuild.js --bootstrap-bucket trackingbot-artifactstore-14bqw9w9xtexq --webapp-bucket trackingbot-webappbucket-1ctxb2wumnogj --webapp-bucket-dashboard trackingbot-webappbucketdashboard-107oo09s9fsk6 --botname TrackingBot --model LexAppBuilder/model/TrackingBotModel.json --cognito-poolid us-east-1:657e53de-93e7-4c74-8c08-0c6

19:22:13
[Container] 2017/06/15 19:22:13 Phase complete: BUILD Success: false

19:22:13
[Container] 2017/06/15 19:22:13 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: node masterBuild.js --bootstrap-bucket trackingbot-artifactstore-14bqw9w9xtexq --webapp-bucket trackingbot-webappbucket-1ctxb2wumnogj --webapp-bucket-dashboard trackingbot-webappbucketdashboard-107oo09s9fsk6 --botname TrackingBot --model LexAppBuilder/model/TrackingBotModel.js

**Comment by GeorgiMateev** [comment]
I changed 3 lines and managed to build the bot. It's working!
Here is a pull request:
[https://github.com/awslabs/aws-ai-tracking-bot/pull/2](https://github.com/awslabs/aws-ai-tracking-bot/pull/2)

**Comment by bobpskier** [comment]
Thanks for identifying this. Definitely a defect in the code. However it looks like either an sdk or s3 runtime change exposed the failure. This aspect of the code has been working for several months. We'll accept your pull request in short order. Thanks again!

**Comment by bobpskier** [comment]
Merged to master from development. Tested on CodePipeline/CodeBuild from master branch. Issue should be resolved.
